/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Capsule {
  index: number
  size: number
  hash: string
  encrypted: boolean
  compressed: boolean
}
export interface EncryptionInfo {
  algorithm: string
  keyDerivation: string
  iterations: number
  salt: string
}
export interface CompressionInfo {
  algorithm: string
  level: number
  originalSize: number
}
export interface CapsuleMetadata {
  originalSize: number
  capsuleCount: number
  capsuleSizes: Array<number>
  checksum: string
  chunkingAlgorithm: string
  consensusVersion: string
  encryptionInfo?: EncryptionInfo
  compressionInfo?: CompressionInfo
}
export interface CapsuleSet {
  id: string
  capsules: Array<Capsule>
  metadata: CapsuleMetadata
}
export declare function createDataCapsule(bufferData: Buffer, outputDirectory: string, postProcessPadding: boolean, encryptionKey?: string | undefined | null): CapsuleSet
export declare function extractDataCapsule(capsuleSetPath: string, decryptionKey?: string | undefined | null): Buffer
export declare function createDataCapsuleFromFile(inputFilePath: string, outputDirectory: string, postProcessPadding: boolean, encryptionKey?: string | undefined | null): CapsuleSet
export declare function extractDataCapsuleToFile(capsuleSetPath: string, outputFilePath: string, decryptionKey?: string | undefined | null): void
export declare function loadCapsuleSet(path: string): CapsuleSet
export declare function reconstructFileFromCapsules(capsuleSet: CapsuleSet, capsulesDir: string, outputFilePath: string, decryptionKey?: string | undefined | null): void
export declare function isValidCapsuleFile(filePath: string): boolean
export declare function getCapsuleFileInfo(filePath: string): CapsuleFileInfo | null
export declare function calculateStorageOverhead(originalSize: number, capsuleCount: number): number
export declare function getCapsuleSizes(): Array<number>
export declare function getConsensusVersion(): string
export declare function validateConsensusParameters(capsuleSet: CapsuleSet): boolean
export interface CapsuleFileInfo {
  magic: string
  version: number
  capsuleIndex: number
  capsuleSize: number
  dataSize: number
  isEncrypted: boolean
  isCompressed: boolean
  checksum: string
}
